schema_version = "1.0.0"

id = "fluffy_computing_machine"
version = "1.0.0"

name = "Fluffy Computing Machine"
tagline = "Yo"
maintainer = "Isamu Mogi <dyob@lunaport.net>"
type = "add-on"

website = "https://github.com/saturday06/fluffy-computing-machine"

tags = ["Modeling"]

blender_version_min = "4.2.0"
blender_version_max = "5.1.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2025 Isamu Mogi"]

[permissions]
files = "Yo"
